truncate table rules.t_dsl_expander cascade;
truncate table rules.t_dslr_rule cascade;
truncate table rules.t_rule_package cascade;

insert into rules.t_rule_package(id, package_name, description)
  values(1, 'at.vaeb.kv.rules.test', 'Test package');

insert into rules.t_dslr_rule(id, rule_name, rule_package_id, definition) 
  values(2, 'TestDSLRRule', 1, E'package at.vaeb.kv.rules.test\n\nimport at.vaeb.kv.ka.sample.record.KAInputRecord;\nimport at.vaeb.kv.ka.sample.record.ValidationResultCollector;\n\nimport org.apache.commons.lang3.StringUtils;\nimport java.time.LocalDate;\n\nglobal ValidationResultCollector validationResultCollector;\n\nrule "Person soll einen Vornamen haben"\n\twhen\n\t\tDer Spitalsaufenthalt\n\t\t- beinhaltet keinen Vornamen\n\tthen\n\t\tWarnung Der Spitalsaufenthalt beinhaltet keinen Vornamen\nend\n\nrule "Person muss einen Nachnamen haben"\n\twhen\n\t\tDer Spitalsaufenthalt\n\t\t- beinhaltet keinen Nachnamen\n\tthen\n\t\tFehler Der Spitalsaufenthalt beinhaltet keinen Nachnamen\nend\n\nrule "Spitalsaufenthalt muss ein Datum von beinhalten"\n\twhen\n\t\tDer Spitalsaufenthalt\n\t\t- beinhaltet kein Datum von\n\tthen\n\t\tFehler Der Spitalsaufenthalt beinhaltet kein Datum von\nend\n\nrule "Der Nachname muss mindestens 5 Zeichen lang sein"\n\twhen\n\t\tDer Spitalsaufenthalt\n\t\t- der Nachname ist kuerzer as 5 Zeichen\n\tthen\n\t\tFehler Der Nachname ist kuerzer als 5 Zeichen\nend\n\nrule "Der Aufenthalt darf maximal 30 Tage dauern"\n\twhen\n\t\tDer Spitalsaufenthalt\n\t\t- laenger als 30 Tage ist\n\tthen\n\t\tWarnung Der Spitalsaufenthalt soll maximal 30 Tage dauern\nend');

insert into rules.t_dsl_expander(id, expander_name, rule_package_id, definition)
  values(3, 'TestDslExpander', 1, E'[condition][KAInputRecord] Der Spitalsaufenthalt=$kaRecord:KAInputRecord()\n[condition][KAInputRecord] - beinhaltet keinen Vornamen=eval(StringUtils.isBlank($kaRecord.getVorname()))\n[condition][KAInputRecord] - beinhaltet keinen Nachnamen=eval(StringUtils.isBlank($kaRecord.getNachname()))\n[condition][KAInputRecord] - beinhaltet kein Datum von=eval($kaRecord.getDatumVon() == null)\n[condition][KAInputRecord] - der Nachname ist kuerzer as {minNachnameLength} Zeichen=eval(!StringUtils.isBlank($kaRecord.getNachname()) && $kaRecord.getNachname().length() < {minNachnameLength})\n[condition][KAInputRecord] - laenger als {maxAufenthaltLength} Tage ist=eval($kaRecord.getAufenthaltsdauer() > {maxAufenthaltLength})\n[consequence][]Warnung {text}=validationResultCollector.addWarning(\"{text}\");\n[consequence][]Fehler {text}=validationResultCollector.addError(\"{text}\");\n[consequence][]Ignorieren=');